FROM nginx:alpine
LABEL authors="E.V.Steshenkova"

COPY index.html /usr/share/nginx/html/index.html
COPY style.css /usr/share/nginx/html/css/style.css
COPY script.js /usr/share/nginx/html/js/script.js
